name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PORT: 8000
      DB_NAME: indexer
      DB_SECRET: qwert
      DJANGO_SECRET: "FDJDSLJFHUDHJCTKLLLCMNII(****#TEFF"
      HOST: localhost
      API_SECRET: "test"
      SERVICE_NAME: "IETF BibXML service"
      CONTACT_EMAIL: "test@email.com"
      DEBUG: 1
      SNAPSHOT: "test"
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image and run the tests
        run: docker compose -f docker-compose.test.yml up --exit-code-from test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
