name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PORT: 8000
      DB_NAME: indexer
      DB_SECRET: qwert
      DJANGO_SECRET: "FDJDSLJFHUDHJCTKLLLCMNII(****#TEFF"
      HOST: localhost
      API_SECRET: "test"
      SERVICE_NAME: "IETF BibXML service"
      CONTACT_EMAIL: "test@email.com"
      DEBUG: 1
      SNAPSHOT: "test"
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - name: Install mypy
        run: pip install "mypy<1.4.1" && pip install -r requirements.txt
      - name: Run mypy
        run: mypy --ignore-missing-imports --install-types --non-interactive .
      - name: Build the Docker image
        run: docker compose -f docker-compose.test.yml build
      - name: Run tests
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: docker compose -f docker-compose.test.yml up --exit-code-from test
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
