name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PORT: 8000
      DB_NAME: test
      DB_SECRET: secret
      DJANGO_SECRET: "DJANGOSECRETEHEHEH(****#TEFF"
      HOST: localhost
      API_SECRET: "secret"
      SERVICE_NAME: "IETF BibXML service test"
      CONTACT_EMAIL: "test@email.com"
      DEBUG: 1
      SNAPSHOT: "test"

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose -f docker-compose.test.yml up
    - name: Stop Containers
      if: always()
      run: docker-compose down
